import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-indigo-900`}>
        <Image width={10000} height={10000} alt="cover" src="/images/cover.jpg" className="absolute object-cover w-full h-full" />
        <div className="absolute inset-0 bg-black opacity-25"></div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
